#!/usr/bin/env bash
# working nginx web server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# working nginx web server
sudo echo "Hello World" | sudo tee /var/www/html/index.htmlsudo
sudo service nginx start