#!/usr/bin/env bash
# configures nginx config file to redirect

oldtext="^\tlocation / {"
newtext="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocationv;"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo fuser -k 80/tcp
sudo fuser -k 443/tcp
sudo sed -i "s@$oldtext@$newtext@" /etc/nginx/sites-available/default
sudo service nginx restart
Footer
