#!/usr/bin bash
# this is a script to configure multiple web servers with nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
# firewall
sudo ufw allow 'Ngnix HTTP'

# html file
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo sh -c "echo Ceci n\'est pas une page > /var/www/html/error404.html"

find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
replace404="\terror_page 404 /error404.html;\n\n\tadd_header X-Served-By $HOSTNAME;\n\n\tlocation / {"

sudo sed -i "s@$find@$replace404@" /etc/nginx/sites-available/default
sudo sed -i "s@$find@$replace301@" /etc/nginx/sites-available/default
# restart / reload

sudo service nginx restart
